/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { YidengContract } from "./YidengContract";
export * as factories from "./factories";
export { YidengContract__factory } from "./factories/YidengContract__factory";
